Arrays hw
aepetrov66/AQA_MTS pull request #2
Opened 2023-12-02 21:44 UTC by aepetrov66

2023-12-04 13:10 UTC, wildpioneer requested changes

2023-12-04 13:10 UTC, wildpioneer commented on ArraysHW/Exercise1.cs
> +                    flag = true;
После найденного числа можно остановить цикл командой break, так как нам дальше не надо искать

2023-12-26 08:56 UTC, wildpioneer commented
Планируешь исправлять ошибки или можно закрывать этот PR?

2024-01-08 02:58 UTC, aepetrov66 commented
Добавил break

2024-01-29 09:36 UTC, wildpioneer commented
Проверено

2024-01-29 09:36 UTC, closed without merging